"""empty message

Revision ID: 13431f1d257e
Revises: 
Create Date: 2023-05-23 11:33:09.851164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13431f1d257e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
